// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIInfo Api info
//
// swagger:model ApiInfo
type APIInfo struct {

	// has provided spec
	HasProvidedSpec *bool `json:"hasProvidedSpec,omitempty"`

	// has reconstructed spec
	HasReconstructedSpec *bool `json:"hasReconstructedSpec,omitempty"`

	// id
	ID uint32 `json:"id,omitempty"`

	// API name
	Name string `json:"name,omitempty"`

	// port
	Port int64 `json:"port,omitempty"`
}

// Validate validates this Api info
func (m *APIInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Api info based on context it is used
func (m *APIInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIInfo) UnmarshalBinary(b []byte) error {
	var res APIInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
