const ROOT_PATH = "/";

const INVENTORY_ROOT_PATH = "/inventory";
const INVENTORY_PATHS = {
  INVENTORY_PATH_INTERNAL: `${INVENTORY_ROOT_PATH}/internal`,
  INVENTORY_PATH_EXTERNAL: `${INVENTORY_ROOT_PATH}/external`,
};

const EVENTS_ROOT_PATH = "/events";
const EVENTS_PATHS = {
  EVENTS_PATH_TABLE_VIEW: `${EVENTS_ROOT_PATH}/tableView`,
  EVENTS_PATH_GRAPH_VIEW: `${EVENTS_ROOT_PATH}/graphView`,
};

const REVIEWER_ROOT_PATH = "/reviewer";
const REVIEWER_PATHS = {};

const TRACE_SOURCES_ROOT_PATH = "/trace-sources";
const TRACE_SOURCES_PATHS = {
  TRACE_SOURCES_PATH_NEW: `${TRACE_SOURCES_ROOT_PATH}/new`,
};

const Path = {
  ROOT_PATH,
  INVENTORY_ROOT_PATH,
  ...INVENTORY_PATHS,
  EVENTS_ROOT_PATH,
  ...EVENTS_PATHS,
  REVIEWER_ROOT_PATH,
  ...REVIEWER_PATHS,
  TRACE_SOURCES_ROOT_PATH,
  ...TRACE_SOURCES_PATHS,
};

export default Path;
