// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.1-0.20220609223533-7da811e1cf30 DO NOT EDIT.
package restapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	externalRef0 "github.com/openclarity/apiclarity/api3/common"
)

// Defines values for BFLAStatus.
const (
	LEARNING         BFLAStatus = "LEARNING"
	LEGITIMATE       BFLAStatus = "LEGITIMATE"
	NOSPEC           BFLAStatus = "NO_SPEC"
	SUSPICIOUSHIGH   BFLAStatus = "SUSPICIOUS_HIGH"
	SUSPICIOUSMEDIUM BFLAStatus = "SUSPICIOUS_MEDIUM"
)

// Defines values for DetectedUserSource.
const (
	BASIC           DetectedUserSource = "BASIC"
	JWT             DetectedUserSource = "JWT"
	KONGXCONSUMERID DetectedUserSource = "KONG_X_CONSUMER_ID"
)

// Defines values for OperationEnum.
const (
	Approve     OperationEnum = "approve"
	ApproveUser OperationEnum = "approve_user"
	Deny        OperationEnum = "deny"
	DenyUser    OperationEnum = "deny_user"
)

// Defines values for SpecType.
const (
	NONE          SpecType = "NONE"
	PROVIDED      SpecType = "PROVIDED"
	RECONSTRUCTED SpecType = "RECONSTRUCTED"
)

// APIEventAnnotations defines model for APIEventAnnotations.
type APIEventAnnotations struct {
	BflaStatus           BFLAStatus    `json:"bflaStatus"`
	DestinationK8sObject *K8sObjectRef `json:"destinationK8sObject,omitempty"`
	DetectedUser         *DetectedUser `json:"detectedUser,omitempty"`
	External             bool          `json:"external"`
	MismatchedScopes     bool          `json:"mismatchedScopes"`
	SourceK8sObject      *K8sObjectRef `json:"sourceK8sObject,omitempty"`
}

// AuthorizationModel defines model for AuthorizationModel.
type AuthorizationModel struct {
	Learning   bool                          `json:"learning"`
	Operations []AuthorizationModelOperation `json:"operations"`
	SpecType   SpecType                      `json:"specType"`
}

// AuthorizationModelAudience defines model for AuthorizationModelAudience.
type AuthorizationModelAudience struct {
	Authorized    bool           `json:"authorized"`
	EndUsers      []DetectedUser `json:"end_users"`
	External      bool           `json:"external"`
	K8sObject     *K8sObjectRef  `json:"k8s_object,omitempty"`
	LastTime      *time.Time     `json:"lastTime,omitempty"`
	StatusCode    int            `json:"statusCode"`
	WarningStatus BFLAStatus     `json:"warningStatus"`
}

// AuthorizationModelNotification defines model for AuthorizationModelNotification.
type AuthorizationModelNotification struct {
	Learning         bool                          `json:"learning"`
	NotificationType string                        `json:"notificationType"`
	Operations       []AuthorizationModelOperation `json:"operations"`
	SpecType         SpecType                      `json:"specType"`
}

// AuthorizationModelOperation defines model for AuthorizationModelOperation.
type AuthorizationModelOperation struct {
	Audience []AuthorizationModelAudience `json:"audience"`
	Method   string                       `json:"method"`
	Path     string                       `json:"path"`
	Tags     []string                     `json:"tags"`
}

// BFLAStatus defines model for BFLAStatus.
type BFLAStatus string

// DetectedUser defines model for DetectedUser.
type DetectedUser struct {
	Id        string             `json:"id"`
	IpAddress string             `json:"ip_address"`
	Source    DetectedUserSource `json:"source"`
}

// DetectedUserSource defines model for DetectedUser.Source.
type DetectedUserSource string

// K8sObjectRef defines model for K8sObjectRef.
type K8sObjectRef struct {
	ApiVersion string `json:"apiVersion"`
	Kind       string `json:"kind"`
	Name       string `json:"name"`
	Namespace  string `json:"namespace"`
	Uid        string `json:"uid"`
}

// OperationEnum defines model for OperationEnum.
type OperationEnum string

// SpecType defines model for SpecType.
type SpecType string

// GetApiFindingsParams defines parameters for GetApiFindings.
type GetApiFindingsParams struct {
	// Should findings include sensitive data ?
	Sensitive *externalRef0.Sensitive `form:"sensitive,omitempty" json:"sensitive,omitempty"`
}

// PostAuthorizationModelApiIDJSONBody defines parameters for PostAuthorizationModelApiID.
type PostAuthorizationModelApiIDJSONBody = AuthorizationModel

// PutAuthorizationModelApiIDApproveParams defines parameters for PutAuthorizationModelApiIDApprove.
type PutAuthorizationModelApiIDApproveParams struct {
	Method       string `form:"method" json:"method"`
	Path         string `form:"path" json:"path"`
	K8sClientUid string `form:"k8sClientUid" json:"k8sClientUid"`
}

// PutAuthorizationModelApiIDDenyParams defines parameters for PutAuthorizationModelApiIDDeny.
type PutAuthorizationModelApiIDDenyParams struct {
	Method       string `form:"method" json:"method"`
	Path         string `form:"path" json:"path"`
	K8sClientUid string `form:"k8sClientUid" json:"k8sClientUid"`
}

// PutAuthorizationModelApiIDLearningStartParams defines parameters for PutAuthorizationModelApiIDLearningStart.
type PutAuthorizationModelApiIDLearningStartParams struct {
	NrTraces *int `form:"nr_traces,omitempty" json:"nr_traces,omitempty"`
}

// PostAuthorizationModelApiIDJSONRequestBody defines body for PostAuthorizationModelApiID for application/json ContentType.
type PostAuthorizationModelApiIDJSONRequestBody = PostAuthorizationModelApiIDJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get findings for an API and module
	// (GET /apiFindings/{apiID})
	GetApiFindings(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID, params GetApiFindingsParams)

	// (GET /authorizationModel/{apiID})
	GetAuthorizationModelApiID(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)

	// (POST /authorizationModel/{apiID})
	PostAuthorizationModelApiID(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)

	// (PUT /authorizationModel/{apiID}/approve)
	PutAuthorizationModelApiIDApprove(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID, params PutAuthorizationModelApiIDApproveParams)

	// (PUT /authorizationModel/{apiID}/deny)
	PutAuthorizationModelApiIDDeny(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID, params PutAuthorizationModelApiIDDenyParams)

	// (PUT /authorizationModel/{apiID}/detection/start)
	PutAuthorizationModelApiIDDetectionStart(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)

	// (PUT /authorizationModel/{apiID}/detection/stop)
	PutAuthorizationModelApiIDDetectionStop(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)

	// (PUT /authorizationModel/{apiID}/learning/start)
	PutAuthorizationModelApiIDLearningStart(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID, params PutAuthorizationModelApiIDLearningStartParams)

	// (PUT /authorizationModel/{apiID}/learning/stop)
	PutAuthorizationModelApiIDLearningStop(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)

	// (POST /authorizationModel/{apiID}/reset)
	PostAuthorizationModelApiIDReset(w http.ResponseWriter, r *http.Request, apiID externalRef0.ApiID)
	// Get the event with the annotations and bfla status
	// (GET /event/{id})
	GetEvent(w http.ResponseWriter, r *http.Request, id int)

	// (PUT /event/{id}/{operation})
	PutEventIdOperation(w http.ResponseWriter, r *http.Request, id int, operation OperationEnum)
	// Get the version of this Module
	// (GET /version)
	GetVersion(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiFindings operation middleware
func (siw *ServerInterfaceWrapper) GetApiFindings(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiFindingsParams

	// ------------- Optional query parameter "sensitive" -------------
	if paramValue := r.URL.Query().Get("sensitive"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "sensitive", r.URL.Query(), &params.Sensitive)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sensitive", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiFindings(w, r, apiID, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetAuthorizationModelApiID operation middleware
func (siw *ServerInterfaceWrapper) GetAuthorizationModelApiID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthorizationModelApiID(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostAuthorizationModelApiID operation middleware
func (siw *ServerInterfaceWrapper) PostAuthorizationModelApiID(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthorizationModelApiID(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutAuthorizationModelApiIDApprove operation middleware
func (siw *ServerInterfaceWrapper) PutAuthorizationModelApiIDApprove(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutAuthorizationModelApiIDApproveParams

	// ------------- Required query parameter "method" -------------
	if paramValue := r.URL.Query().Get("method"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "method"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "method", r.URL.Query(), &params.Method)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "method", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------
	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Required query parameter "k8sClientUid" -------------
	if paramValue := r.URL.Query().Get("k8sClientUid"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "k8sClientUid"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "k8sClientUid", r.URL.Query(), &params.K8sClientUid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "k8sClientUid", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAuthorizationModelApiIDApprove(w, r, apiID, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutAuthorizationModelApiIDDeny operation middleware
func (siw *ServerInterfaceWrapper) PutAuthorizationModelApiIDDeny(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutAuthorizationModelApiIDDenyParams

	// ------------- Required query parameter "method" -------------
	if paramValue := r.URL.Query().Get("method"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "method"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "method", r.URL.Query(), &params.Method)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "method", Err: err})
		return
	}

	// ------------- Required query parameter "path" -------------
	if paramValue := r.URL.Query().Get("path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "path", r.URL.Query(), &params.Path)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		return
	}

	// ------------- Required query parameter "k8sClientUid" -------------
	if paramValue := r.URL.Query().Get("k8sClientUid"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "k8sClientUid"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "k8sClientUid", r.URL.Query(), &params.K8sClientUid)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "k8sClientUid", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAuthorizationModelApiIDDeny(w, r, apiID, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutAuthorizationModelApiIDDetectionStart operation middleware
func (siw *ServerInterfaceWrapper) PutAuthorizationModelApiIDDetectionStart(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAuthorizationModelApiIDDetectionStart(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutAuthorizationModelApiIDDetectionStop operation middleware
func (siw *ServerInterfaceWrapper) PutAuthorizationModelApiIDDetectionStop(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAuthorizationModelApiIDDetectionStop(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutAuthorizationModelApiIDLearningStart operation middleware
func (siw *ServerInterfaceWrapper) PutAuthorizationModelApiIDLearningStart(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutAuthorizationModelApiIDLearningStartParams

	// ------------- Optional query parameter "nr_traces" -------------
	if paramValue := r.URL.Query().Get("nr_traces"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "nr_traces", r.URL.Query(), &params.NrTraces)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "nr_traces", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAuthorizationModelApiIDLearningStart(w, r, apiID, params)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutAuthorizationModelApiIDLearningStop operation middleware
func (siw *ServerInterfaceWrapper) PutAuthorizationModelApiIDLearningStop(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutAuthorizationModelApiIDLearningStop(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostAuthorizationModelApiIDReset operation middleware
func (siw *ServerInterfaceWrapper) PostAuthorizationModelApiIDReset(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "apiID" -------------
	var apiID externalRef0.ApiID

	err = runtime.BindStyledParameterWithLocation("simple", false, "apiID", runtime.ParamLocationPath, chi.URLParam(r, "apiID"), &apiID)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "apiID", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthorizationModelApiIDReset(w, r, apiID)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetEvent operation middleware
func (siw *ServerInterfaceWrapper) GetEvent(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEvent(w, r, id)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutEventIdOperation operation middleware
func (siw *ServerInterfaceWrapper) PutEventIdOperation(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, chi.URLParam(r, "id"), &id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "operation" -------------
	var operation OperationEnum

	err = runtime.BindStyledParameterWithLocation("simple", false, "operation", runtime.ParamLocationPath, chi.URLParam(r, "operation"), &operation)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "operation", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutEventIdOperation(w, r, id, operation)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/apiFindings/{apiID}", wrapper.GetApiFindings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/authorizationModel/{apiID}", wrapper.GetAuthorizationModelApiID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/authorizationModel/{apiID}", wrapper.PostAuthorizationModelApiID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/authorizationModel/{apiID}/approve", wrapper.PutAuthorizationModelApiIDApprove)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/authorizationModel/{apiID}/deny", wrapper.PutAuthorizationModelApiIDDeny)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/authorizationModel/{apiID}/detection/start", wrapper.PutAuthorizationModelApiIDDetectionStart)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/authorizationModel/{apiID}/detection/stop", wrapper.PutAuthorizationModelApiIDDetectionStop)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/authorizationModel/{apiID}/learning/start", wrapper.PutAuthorizationModelApiIDLearningStart)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/authorizationModel/{apiID}/learning/stop", wrapper.PutAuthorizationModelApiIDLearningStop)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/authorizationModel/{apiID}/reset", wrapper.PostAuthorizationModelApiIDReset)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/event/{id}", wrapper.GetEvent)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/event/{id}/{operation}", wrapper.PutEventIdOperation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.GetVersion)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa34/aOBD+VyLfPaawvb5UvLFAt7l2ARHonVRVyJsMi7uJ7drO9jiU//1kJ+SnYXfZ",
	"VqU9pJUWnMn4m2++8Tg4WxSwmDMKVEnU2yIZrCHG5mN/6o3ugao+pUxhRRg1w1wwDkIRMN9uVhH2FVaJ",
	"+fa7gBXqod+6pdNu7rF7+eZ9P7dMXRSCVIQar+9ey8nNZwjUQx4KwxmsMh8KAgXhQoJ46N5h1TZ1Efyj",
	"QFAc6fvUhgPqoRvGIsBUX42JjLEK1hD6AeNZpG0ryRIRwJHwUxcJ+JIQASHqfazyWAFnQfIpdVE/UWsm",
	"yL+GvmsWQtROTARYUEJv7dC1ZZlSoiB+MH/tSSc7J9pjPgcWAm8MORyCuRk77Nbf2TUZKRzU0LplYJ+K",
	"SVnGv5WZfhISoAG0GcK5rZ7OxhHQcJlIEI+nqCmyJieHRXf3Wi7ZUYUQYanmJDYxrpiIsUI9FGIFL5Qe",
	"LYBIJTRxOjtGagMWQgULoQpuM+RfM46fXtmNJJYculW+axKvYGlO/LgUj5kiKxJkUtSJjaLJCvU+Fqg7",
	"nW7jD3PySocSM9plHCjmpLPBcWSPD0uozZG6Ty0VlNrrtiwhizxL4R5ZoIX2LVqMQa1ZVfmlODhWa+sF",
	"hW/rxdC2qM3SEIPxW8zslhHmnm3Zrmirt0VAk1h7Gk+W/nQ0QC56P+rPxt74yny88ubedX8+Qi7yF/7U",
	"G3iThb+8Hg29xXV97K139bYyXxnAsNFT6jkhdsIIX+IwFCDtpGR9oor/z7/myEWXfd/TMbybjK+Wfy8H",
	"k7G/uB7Nlt7QAq3BJdEE5o5rALTOautDW1icfAAhc9G10N4Rao+S4hj2XpAcB/ariZW0RjiJicdMnU9U",
	"detWMdtUUpTRyBBcEo05F+xeewiBbowjM2AWpXw0+2wTg1/pYaX0xlpf09nkgzccDZGLZiOduflsMZiP",
	"rJnTCqErpr2EIANBeFbxeoc1iLAgauNcszCJwOlPPV0NREVQv67rALnofpc4dNG56LzMW7levlAPvepc",
	"dF6hrH5NpvUy94bQkNBb2d1iTrxhqsdvQVnAyDvprJhwVvkdDls5mDoVELEB6TqYhnq443gxjyAGqiB0",
	"bjYO4GCdG1W7theiHroC1S/RGJQCx6BMf/24RURjyFeITGnIAEZVoSiRgJvvUSvL4TPX976ZJ62s6kc6",
	"LEPq+kAlUeQeUPpJRyA5ozKrvz8uLvS/gFEFVGUVyaO8t3Q/y6wuv3mQU68g30iykX2TaGdn4lwmNIwg",
	"22WvcBKpHwGZk1lOnA3ySAgmHFFauEgmcYzFJpNbKWSt6kzJRrq5QvUNXdxqmpZCaSu53WpzrZ6eqr+R",
	"/B690Wknyk+CQLemn0xM2W4nezQzbZUzaZHDlMmfTw9fEpDqkoWb7yyFtCW+l6eX+19Dn4dXs+5uJ6S3",
	"g4lNxsk+FfeLPdRJtmyD4ksCYlPCKB4x9uNo7UftnvLwnu3n7rUcRASoWpCn4TqR3cMvXUERC3D04nF1",
	"ZJ4jnl5Ew+zx41xB5wo6V5CCwMQhFRbqqGLKPfjGwS+86z6L7tkbn6rcGH+e2hg/i+0stgNi2x1OHb20",
	"vYfiAOREV7Y97ZmKpRI4AIksvbg4WTpL9RSletSyWCr1vCqepXZQagJk9kPqk39Bm5k7z+r636sL7oGq",
	"7paEB3+XN+8rPUouj3uG/OZ9a9/RTOtFK9sRzdRzjJ3zlai1g2vWzbMPtQYHSmP9tXKDOQbR7Dpy987R",
	"3ie5kvnutiA8PdQwDEgvLN9t+B4Jca1eWGXOB1cCazLqR8nnOv8hvx7cl+8nWM+qdwrP7Ry2ctSayPwU",
	"3Xb2vHt74CSymcHcQbJw9aEaF+zCslf5Xg7s7KbpfwEAAP//Dh2QWvMpAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../../../../../../api3/common/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
