// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.1-0.20220609223533-7da811e1cf30 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for APIClarityFeatureEnum.
const (
	Bfla              APIClarityFeatureEnum = "bfla"
	Fuzzer            APIClarityFeatureEnum = "fuzzer"
	SpecDiffer        APIClarityFeatureEnum = "spec_differ"
	Specdiffs         APIClarityFeatureEnum = "specdiffs"
	Specreconstructor APIClarityFeatureEnum = "specreconstructor"
	Traceanalyzer     APIClarityFeatureEnum = "traceanalyzer"
)

// Defines values for AlertSeverityEnum.
const (
	ALERTCRITICAL AlertSeverityEnum = "ALERT_CRITICAL"
	ALERTINFO     AlertSeverityEnum = "ALERT_INFO"
	ALERTWARN     AlertSeverityEnum = "ALERT_WARN"
)

// Defines values for ApiEventSortKey.
const (
	ApiType         ApiEventSortKey = "apiType"
	DestinationIP   ApiEventSortKey = "destinationIP"
	DestinationPort ApiEventSortKey = "destinationPort"
	HostSpecName    ApiEventSortKey = "hostSpecName"
	Method          ApiEventSortKey = "method"
	Path            ApiEventSortKey = "path"
	SourceIP        ApiEventSortKey = "sourceIP"
	SpecDiffType    ApiEventSortKey = "specDiffType"
	StatusCode      ApiEventSortKey = "statusCode"
	Time            ApiEventSortKey = "time"
)

// Defines values for ApiInventorySortKey.
const (
	HasProvidedSpec      ApiInventorySortKey = "hasProvidedSpec"
	HasReconstructedSpec ApiInventorySortKey = "hasReconstructedSpec"
	Name                 ApiInventorySortKey = "name"
	Port                 ApiInventorySortKey = "port"
)

// Defines values for ApiTypeEnum.
const (
	EXTERNAL ApiTypeEnum = "EXTERNAL"
	INTERNAL ApiTypeEnum = "INTERNAL"
)

// Defines values for DiffType.
const (
	GENERALDIFF DiffType = "GENERAL_DIFF"
	NODIFF      DiffType = "NO_DIFF"
	SHADOWDIFF  DiffType = "SHADOW_DIFF"
	ZOMBIEDIFF  DiffType = "ZOMBIE_DIFF"
)

// Defines values for HttpMethod.
const (
	CONNECT HttpMethod = "CONNECT"
	DELETE  HttpMethod = "DELETE"
	GET     HttpMethod = "GET"
	HEAD    HttpMethod = "HEAD"
	OPTIONS HttpMethod = "OPTIONS"
	PATCH   HttpMethod = "PATCH"
	POST    HttpMethod = "POST"
	PUT     HttpMethod = "PUT"
	TRACE   HttpMethod = "TRACE"
)

// Defines values for Severity.
const (
	CRITICAL Severity = "CRITICAL"
	HIGH     Severity = "HIGH"
	INFO     Severity = "INFO"
	LOW      Severity = "LOW"
	MEDIUM   Severity = "MEDIUM"
)

// Defines values for SpecType.
const (
	NONE          SpecType = "NONE"
	PROVIDED      SpecType = "PROVIDED"
	RECONSTRUCTED SpecType = "RECONSTRUCTED"
)

// Description of APIClarity feature and the list of API hosts (in the form 'host:port') the feature requires to get trace for
type APIClarityFeature struct {
	// Short human readable description of the feature
	FeatureDescription *string `json:"featureDescription,omitempty"`

	// APIClarity Feature Name
	FeatureName  APIClarityFeatureEnum `json:"featureName"`
	HostsToTrace *[]string             `json:"hostsToTrace,omitempty"`
}

// APIClarity Feature Name
type APIClarityFeatureEnum string

// List of APIClarity features and for each feature the list of API hosts (in the form 'host:port') the feature requires to get trace for
type APIClarityFeatureList struct {
	Features *[]APIClarityFeature `json:"features,omitempty"`
}

// An API Finding
type APIFinding struct {
	// Could be any opaque JSON object
	AdditionalInfo *map[string]interface{} `json:"additional_info,omitempty"`

	// Human readable description of the finding
	Description string `json:"description"`

	// Human readable name of the finding
	Name string `json:"name"`

	// JSON pointer to the location of the finding in the specification. See https://datatracker.ietf.org/doc/html/rfc6901. If at the time of creation of the finding, there is no specification, then this field is an empty string.
	ProvidedSpecLocation *string `json:"provided_spec_location,omitempty"`

	// JSON pointer to the location of the finding in the specification. See https://datatracker.ietf.org/doc/html/rfc6901. If at the time of creation of the finding, there is no specification, then this field is an empty string.
	ReconstructedSpecLocation *string `json:"reconstructed_spec_location,omitempty"`

	// Severity of a finding
	Severity Severity `json:"severity"`

	// Name of the module which created this finding
	Source string `json:"source"`

	// Type of the finding
	Type string `json:"type"`
}

// A group of findings
type APIFindings struct {
	// A list of findings
	Items *[]APIFinding `json:"items,omitempty"`
}

// AlertSeverityEnum defines model for AlertSeverityEnum.
type AlertSeverityEnum string

// ApiCount defines model for ApiCount.
type ApiCount struct {
	ApiHostName *string `json:"apiHostName,omitempty"`

	// hold the relevant api info id
	ApiInfoId *uint32      `json:"apiInfoId,omitempty"`
	ApiPort   *int         `json:"apiPort,omitempty"`
	ApiType   *ApiTypeEnum `json:"apiType,omitempty"`
	NumCalls  *int         `json:"numCalls,omitempty"`
}

// ApiEvent defines model for ApiEvent.
type ApiEvent struct {
	Alerts *[]ModuleAlert `json:"alerts,omitempty"`

	// hold the relevant api spec info id
	ApiInfoId                *uint32      `json:"apiInfoId,omitempty"`
	ApiType                  *ApiTypeEnum `json:"apiType,omitempty"`
	DestinationIP            *string      `json:"destinationIP,omitempty"`
	DestinationPort          *int         `json:"destinationPort,omitempty"`
	HasProvidedSpecDiff      *bool        `json:"hasProvidedSpecDiff,omitempty"`
	HasReconstructedSpecDiff *bool        `json:"hasReconstructedSpecDiff,omitempty"`
	HostSpecName             *string      `json:"hostSpecName,omitempty"`
	Id                       *uint32      `json:"id,omitempty"`
	Method                   *HttpMethod  `json:"method,omitempty"`
	Path                     *string      `json:"path,omitempty"`
	Query                    *string      `json:"query,omitempty"`
	RequestTime              *time.Time   `json:"requestTime,omitempty"`
	SourceIP                 *string      `json:"sourceIP,omitempty"`
	SpecDiffType             *DiffType    `json:"specDiffType,omitempty"`
	StatusCode               *int         `json:"statusCode,omitempty"`
	Time                     *time.Time   `json:"time,omitempty"`
}

// ApiEventPathAndMethods defines model for ApiEventPathAndMethods.
type ApiEventPathAndMethods struct {
	Methods *[]HttpMethod `json:"methods,omitempty"`
	Path    *string       `json:"path,omitempty"`
}

// ApiEventSortKey defines model for ApiEventSortKey.
type ApiEventSortKey string

// ApiEventSpecDiff defines model for ApiEventSpecDiff.
type ApiEventSpecDiff struct {
	DiffType *DiffType `json:"diffType,omitempty"`

	// New spec json string
	NewSpec string `json:"newSpec"`

	// Old spec json string
	OldSpec string `json:"oldSpec"`
}

// ApiFindingsNotification defines model for ApiFindingsNotification.
type ApiFindingsNotification struct {
	// A list of findings
	Items            *[]APIFinding `json:"items,omitempty"`
	NotificationType string        `json:"notificationType"`
}

// ApiID defines model for ApiID.
type ApiID = int64

// ApiInfo defines model for ApiInfo.
type ApiInfo struct {
	// String representing the entity which created this API. APICLARITY means it has been created by APIClarity on first trace
	CreatedBy            *string `json:"createdBy,omitempty"`
	DestinationNamespace *string `json:"destinationNamespace,omitempty"`
	HasProvidedSpec      *bool   `json:"hasProvidedSpec,omitempty"`
	HasReconstructedSpec *bool   `json:"hasReconstructedSpec,omitempty"`
	Id                   *uint32 `json:"id,omitempty"`

	// API name
	Name *string `json:"name,omitempty"`
	Port *int    `json:"port,omitempty"`
}

// ApiInfoWithType defines model for ApiInfoWithType.
type ApiInfoWithType struct {
	ApiType *ApiTypeEnum `json:"apiType,omitempty"`

	// String representing the entity which created this API. APICLARITY means it has been created by APIClarity on first trace
	CreatedBy            *string `json:"createdBy,omitempty"`
	DestinationNamespace *string `json:"destinationNamespace,omitempty"`
	HasProvidedSpec      *bool   `json:"hasProvidedSpec,omitempty"`
	HasReconstructedSpec *bool   `json:"hasReconstructedSpec,omitempty"`
	Id                   *uint32 `json:"id,omitempty"`

	// API name
	Name *string `json:"name,omitempty"`
	Port *int    `json:"port,omitempty"`
}

// ApiInventorySortKey defines model for ApiInventorySortKey.
type ApiInventorySortKey string

// An object that is returned in all cases of failures
type ApiResponse struct {
	Message string `json:"message"`
}

// ApiTypeEnum defines model for ApiTypeEnum.
type ApiTypeEnum string

// ApiUsage defines model for ApiUsage.
type ApiUsage struct {
	NumOfCalls *int       `json:"numOfCalls"`
	Time       *time.Time `json:"time,omitempty"`
}

// ApiUsages defines model for ApiUsages.
type ApiUsages struct {
	ApisWithDiff *[]ApiUsage `json:"apisWithDiff,omitempty"`
	ExistingApis *[]ApiUsage `json:"existingApis,omitempty"`
	NewApis      *[]ApiUsage `json:"newApis,omitempty"`
}

// ApprovedReview defines model for ApprovedReview.
type ApprovedReview struct {
	ReviewPathItems *[]ReviewPathItem `json:"reviewPathItems,omitempty"`
}

// Base Notification all APIClarity notifications must extend
type BaseNotification struct {
	NotificationType string `json:"notificationType"`
}

// DiffType defines model for DiffType.
type DiffType string

// HitCount defines model for HitCount.
type HitCount struct {
	Count *int64     `json:"count"`
	Time  *time.Time `json:"time,omitempty"`
}

// HttpMethod defines model for HttpMethod.
type HttpMethod string

// MethodAndPath defines model for MethodAndPath.
type MethodAndPath struct {
	Method *HttpMethod         `json:"method,omitempty"`
	Path   *string             `json:"path,omitempty"`
	PathId *openapi_types.UUID `json:"pathId,omitempty"`
}

// ModuleAlert defines model for ModuleAlert.
type ModuleAlert struct {
	Alert *AlertSeverityEnum `json:"alert,omitempty"`

	// Name of the module which created this alert
	ModuleName *string `json:"moduleName,omitempty"`

	// Optional description of reason of the alert
	Reason *string `json:"reason,omitempty"`
}

// ModuleVersion defines model for ModuleVersion.
type ModuleVersion struct {
	Version string `json:"version"`
}

// An object representing the provided and reconstructed API specs
type OpenApiSpecs struct {
	// An object containing info about a spec
	ProvidedSpec *SpecInfo `json:"providedSpec,omitempty"`

	// An object containing info about a spec
	ReconstructedSpec *SpecInfo `json:"reconstructedSpec,omitempty"`
}

// ReviewPathItem defines model for ReviewPathItem.
type ReviewPathItem struct {
	// Group of api event paths (original) that suggestedPath is representing
	ApiEventsPaths *[]ApiEventPathAndMethods `json:"apiEventsPaths,omitempty"`

	// Represents the parameterized path suggested by the engine
	SuggestedPath *string `json:"suggestedPath,omitempty"`
}

// Severity of a finding
type Severity string

// SpecDiffTime defines model for SpecDiffTime.
type SpecDiffTime struct {
	ApiEventId  *uint32    `json:"apiEventId,omitempty"`
	ApiHostName *string    `json:"apiHostName,omitempty"`
	DiffType    *DiffType  `json:"diffType,omitempty"`
	Time        *time.Time `json:"time,omitempty"`
}

// An object containing info about a spec
type SpecInfo struct {
	Tags *[]SpecTag `json:"tags,omitempty"`
}

// SpecTag defines model for SpecTag.
type SpecTag struct {
	Description       *string          `json:"description,omitempty"`
	MethodAndPathList *[]MethodAndPath `json:"methodAndPathList,omitempty"`
	Name              *string          `json:"name,omitempty"`
}

// SpecType defines model for SpecType.
type SpecType string

// An object that is return in cases of success that return nothing.
type SuccessResponse struct {
	Message *string `json:"message,omitempty"`
}

// SuggestedReview defines model for SuggestedReview.
type SuggestedReview struct {
	Id              *uint32           `json:"id,omitempty"`
	ReviewPathItems *[]ReviewPathItem `json:"reviewPathItems,omitempty"`
}

// spec in json or yaml format
type RawSpec struct {
	// spec in json or yaml format
	RawSpec *string `json:"rawSpec,omitempty"`
}

// Sensitive defines model for Sensitive.
type Sensitive = bool

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOPL/KgT3D+wuoI2b9o8Fzm8OruM22k1tw3Y3d1cEASONbG4lkiWppG7hfvYD",
	"KdLWA+0oud6+ujdtJA45w988j/wVJ7wQnAHTCg+/YkEkKUCDtE9LYIpqeg/mIQWVSCo05QwP8XLDyzxF",
	"GWUpZWuFKEvyMgWk/BaUEk3Q33GEqaH/VILc4ggzUgAe4j0ZjrBKNlCQikVGylzjYUZyBRHWW2GI7zjP",
	"gTC82+08tRVvNI/HOZFUb98A0aUMiHlxeEI8Q4cdKKu2IMJSpDeAcqq0I0EbrrRCP1FmVzIuC/SjeTcU",
	"XOoff67euv0SPpVUgkKaozVopCVJ7B4cYSG5AKkpWHHdjou6gAFYpUabsiAMSSApucsBpc1L1LjjPUZK",
	"S8rWeBd5NlML9Ff8fxIyPMQ/DA6KHjgMBx0AJ6wszBkWgBVfmbuYQ6iGwt6hw829IFKSLTb6cXikePih",
	"IcrNnpbf/QmJNpvD/Dug1LTm6JA9MsJg6T9gJSCRkHCmtCwTbcE371KaZcqAZC5CGMm3X8Cs3WU5cSS3",
	"hsa+zMovZvUmgGlH0CuqdFfQq4MNtcxMWTvLuERAks3eeP5Sw1MNTT7JLoKaDqnzTRUPAjpk9oJ+vS0i",
	"SVNqKEl+S1nGu/vHNtzcGX/dIi7IpxLQb8vZFDn2EYbPpBC5NdePsL3NgeHh+cuQnOkpD7x83Pf2d9iz",
	"xCP0AORjJdE13KEV/wgMbYhCdwAMpaAh0ZCG/JU5Rz0phiE6xf+6yz3ES0h+T1NIb63l5zwhYRDsSYJT",
	"pkEa+7J26qhbYiBnrOZEmtGK5gwtAdBGa6GGg4HJBMY6P4I8o6CzMy7Xg5Qng40u8oHMkl//9uL8DMUZ",
	"ItqepWl120RCiGVkHiQgqhDjTcZ2yQhEFcoo5KkhIgxBIfQWVUCcNZD7YSCI3qjBt/O7nK/Vt/Ov5v9b",
	"mu6+nTN4+PZCGJ8MgVkLOP9D9LsgquAeTNR5LD4tPZ3Zw0uZBBxoWvOYgqdlDuhhQ5NNBQGk/kZdX2on",
	"iyM5r81wtRWnXXQy+v32t+tV98RW1rSr+4u5ANGMWjWobk4GYhWIxGgteSmMqL5664TjfZZob/XJqraz",
	"b0bxob9fKslBaq9mXxX4bD+6mixWt/H0zQxH7uF6tJjuH8aLeBWPR1fhVC7omJfMZu9WDhL0kivtC6fO",
	"TiJozDIep11gNjyvqkgJOdwTphERFJlMhqgJ+iaTE42HuKRMv3p5MAETD9Yg3fFzLnWNdXNx5azuJMwV",
	"mS/jWFmMSZ6r0JlB1AWd3EMQG6OP/gXEO+twVoldfT8DSRORng7nMxBLQWnKbOCL50ErqFEcV9eGqLlL",
	"tUsByQXNsj79jd24qKeVJ+7mSpsdR02YWsT7wFeA3vD0MfQutRbvKkpTXRC9CbKtmr/Qiol7oPSKVgLv",
	"JUuJhl9M0gqmCRsZj+hHOcT6KH9PZ/Zpoks15imEVaqfIOIp35oTvRmxtEJNdT2tOCz0crWmCtqedkQl",
	"pwRccql/h2094LpbOptwpzYgqyml7URdl2kpqWW3B9c9Er4rKWuO0QQwfYbyGTyYAwNVBDxUwedPxZmr",
	"dkImyfM0fMAsT3sc0KoA/GkHwW7CCvNZfsr1vmCrwnU+y/Dww2kEXhMFjZ27qG8WV3h3U4kQXzS8gjL9",
	"6/8HI8qoCvpdhbmC7PW2EeRsz301WsSrf7aKnyFeWtiQBCFBAdPmweQM86fehuq80Tw+Q4cTUQGEKUT1",
	"oUXz5HfbevvOGcqoVK67Dmm+ZtzGfJVwI5MOYSsnPD8f9NvZP9SHG1DTrbvKs9tGHkl8R8KKUfs11Rvv",
	"lf2s09uLMcpOofbk1L7b3RwTzoQTLreBuOfuL6qgFdRFV69HotYClOBMQXA0UkmE9IZo015J0KVkkJpO",
	"kOQ5SogCZctuQnM7yYk6WUMpsoZwqK+HFk94BI09YDUU4ulqspiOrnCEJ/9wfx655HsvRFM6Vhaz7Fgl",
	"GuHPv/DC5DphOj9r0N8n31ppVLDQV8Yeff7o18H42wWyLHymJgisR4Kq73Igg4fvdFYYGiH5PaQLuKfw",
	"0MVH2vemUIk9815SLBr7+snSyUEd9zAUqE5iXaIWo1ltTaGiVBrBZw0s7XhJndJHkNPu0tkR8pt6uXnI",
	"X9PZ7UX85k1tSv2v2bvX8cS/XV6OLmbX/untZDpZjK78o98c8rNLqo90sIl//Vg6/i/5XK0WrcWPt5MV",
	"jvDlZHSBIzyfLc3T/L3592JyNVlNcITHs+l0MjavZvNVPJsucYRXi9HYrM1Hq/FlEIiK1Yilc1flhirp",
	"79TCmIW4lVJLmvbDpd4Oh1vrRx28Mw8xPZo9dhpM3/3GXxXv4GyTqJAzzkQ1pW/PxSt6z/DIsceh+QOk",
	"cs7fBOf+sHDaUT1hyD9nAthIUJOd1an026kn/bjcfrxpjHvtxwxlD2wHGdEq8k4OMgUkrshpjpOftjkE",
	"bCsYh5KgbaSUIQnA8tYPCYmgCAwlsmNd9BOXdE0ZyX+u6hVVrtegNFgvrKqXA4y954Ph7jiQGhvsumIv",
	"PHNVadB/z6ZfILUXOMhrSv2qa1hT1jPCLWsT6lZP4lYsZPUBsIuCV7NrHOF3k4v4/TsTDuO3lybw+VFl",
	"hO0886Y+MXY0Hef0va+fmoQVG/duAB4bfD6no/5PU8neuE/4a8KZJpRVn0wyjsgdLzUi1i87bqnJun8l",
	"Y7ivSM9ZtSfuTiKa3xk7uBb1/OW/KPebrzYyX6iADOvyqPhOu95Yp7OpTb2L2R/xxcTk7cVkPJsuV4v3",
	"49XkIpiNl2WSgFJP73NMl7PvcFR1SkXi1hnXG/eV6QldT/ei3vGP1b39W+a/skKW5Mhsyg3Fq8kSl2hL",
	"ihw56dtIPfOQR1E1r/wHe021DVtjXhScoWV1Z/ujh5GgrlrH0SGn4/OzF3Z4JoARQfEQvzp7cfbSDRiN",
	"3PaboLy3P0f68BWXMsdDPCCCDu5f4d3N7t8BAAD///gBn0+/JAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
