// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openclarity/apiclarity/plugins/api/server/models"
)

// GetHostsToTraceOKCode is the HTTP code returned for type GetHostsToTraceOK
const GetHostsToTraceOKCode int = 200

/*GetHostsToTraceOK Success

swagger:response getHostsToTraceOK
*/
type GetHostsToTraceOK struct {

	/*
	  In: Body
	*/
	Payload *models.HostsToTrace `json:"body,omitempty"`
}

// NewGetHostsToTraceOK creates GetHostsToTraceOK with default headers values
func NewGetHostsToTraceOK() *GetHostsToTraceOK {

	return &GetHostsToTraceOK{}
}

// WithPayload adds the payload to the get hosts to trace o k response
func (o *GetHostsToTraceOK) WithPayload(payload *models.HostsToTrace) *GetHostsToTraceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hosts to trace o k response
func (o *GetHostsToTraceOK) SetPayload(payload *models.HostsToTrace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHostsToTraceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetHostsToTraceDefault unknown error

swagger:response getHostsToTraceDefault
*/
type GetHostsToTraceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetHostsToTraceDefault creates GetHostsToTraceDefault with default headers values
func NewGetHostsToTraceDefault(code int) *GetHostsToTraceDefault {
	if code <= 0 {
		code = 500
	}

	return &GetHostsToTraceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get hosts to trace default response
func (o *GetHostsToTraceDefault) WithStatusCode(code int) *GetHostsToTraceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get hosts to trace default response
func (o *GetHostsToTraceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get hosts to trace default response
func (o *GetHostsToTraceDefault) WithPayload(payload *models.APIResponse) *GetHostsToTraceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get hosts to trace default response
func (o *GetHostsToTraceDefault) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHostsToTraceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
