// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostTelemetryHandlerFunc turns a function with the right signature into a post telemetry handler
type PostTelemetryHandlerFunc func(PostTelemetryParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTelemetryHandlerFunc) Handle(params PostTelemetryParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostTelemetryHandler interface for that can handle valid post telemetry params
type PostTelemetryHandler interface {
	Handle(PostTelemetryParams, interface{}) middleware.Responder
}

// NewPostTelemetry creates a new http.Handler for the post telemetry operation
func NewPostTelemetry(ctx *middleware.Context, handler PostTelemetryHandler) *PostTelemetry {
	return &PostTelemetry{Context: ctx, Handler: handler}
}

/* PostTelemetry swagger:route POST /telemetry postTelemetry

Post an http telemetry

*/
type PostTelemetry struct {
	Context *middleware.Context
	Handler PostTelemetryHandler
}

func (o *PostTelemetry) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostTelemetryParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
