// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/apiclarity/api/client/models"
)

// DeleteAPIInventoryAPIIDSpecsReconstructedSpecReader is a Reader for the DeleteAPIInventoryAPIIDSpecsReconstructedSpec structure.
type DeleteAPIInventoryAPIIDSpecsReconstructedSpecReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIInventoryAPIIDSpecsReconstructedSpecReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIInventoryAPIIDSpecsReconstructedSpecOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteAPIInventoryAPIIDSpecsReconstructedSpecOK creates a DeleteAPIInventoryAPIIDSpecsReconstructedSpecOK with default headers values
func NewDeleteAPIInventoryAPIIDSpecsReconstructedSpecOK() *DeleteAPIInventoryAPIIDSpecsReconstructedSpecOK {
	return &DeleteAPIInventoryAPIIDSpecsReconstructedSpecOK{}
}

/* DeleteAPIInventoryAPIIDSpecsReconstructedSpecOK describes a response with status code 200, with default header values.

Success
*/
type DeleteAPIInventoryAPIIDSpecsReconstructedSpecOK struct {
	Payload interface{}
}

func (o *DeleteAPIInventoryAPIIDSpecsReconstructedSpecOK) Error() string {
	return fmt.Sprintf("[DELETE /apiInventory/{apiId}/specs/reconstructedSpec][%d] deleteApiInventoryApiIdSpecsReconstructedSpecOK  %+v", 200, o.Payload)
}
func (o *DeleteAPIInventoryAPIIDSpecsReconstructedSpecOK) GetPayload() interface{} {
	return o.Payload
}

func (o *DeleteAPIInventoryAPIIDSpecsReconstructedSpecOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault creates a DeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault with default headers values
func NewDeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault(code int) *DeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault {
	return &DeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault{
		_statusCode: code,
	}
}

/* DeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault describes a response with status code -1, with default header values.

unknown error
*/
type DeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault struct {
	_statusCode int

	Payload *models.APIResponse
}

// Code gets the status code for the delete API inventory API ID specs reconstructed spec default response
func (o *DeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault) Error() string {
	return fmt.Sprintf("[DELETE /apiInventory/{apiId}/specs/reconstructedSpec][%d] DeleteAPIInventoryAPIIDSpecsReconstructedSpec default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *DeleteAPIInventoryAPIIDSpecsReconstructedSpecDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
