// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/apiclarity/api/client/models"
)

// DeleteControlGatewaysGatewayIDReader is a Reader for the DeleteControlGatewaysGatewayID structure.
type DeleteControlGatewaysGatewayIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteControlGatewaysGatewayIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteControlGatewaysGatewayIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteControlGatewaysGatewayIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteControlGatewaysGatewayIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteControlGatewaysGatewayIDNoContent creates a DeleteControlGatewaysGatewayIDNoContent with default headers values
func NewDeleteControlGatewaysGatewayIDNoContent() *DeleteControlGatewaysGatewayIDNoContent {
	return &DeleteControlGatewaysGatewayIDNoContent{}
}

/* DeleteControlGatewaysGatewayIDNoContent describes a response with status code 204, with default header values.

Success
*/
type DeleteControlGatewaysGatewayIDNoContent struct {
}

func (o *DeleteControlGatewaysGatewayIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /control/gateways/{gatewayId}][%d] deleteControlGatewaysGatewayIdNoContent ", 204)
}

func (o *DeleteControlGatewaysGatewayIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteControlGatewaysGatewayIDNotFound creates a DeleteControlGatewaysGatewayIDNotFound with default headers values
func NewDeleteControlGatewaysGatewayIDNotFound() *DeleteControlGatewaysGatewayIDNotFound {
	return &DeleteControlGatewaysGatewayIDNotFound{}
}

/* DeleteControlGatewaysGatewayIDNotFound describes a response with status code 404, with default header values.

API Gateway not found
*/
type DeleteControlGatewaysGatewayIDNotFound struct {
	Payload *models.APIResponse
}

func (o *DeleteControlGatewaysGatewayIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /control/gateways/{gatewayId}][%d] deleteControlGatewaysGatewayIdNotFound  %+v", 404, o.Payload)
}
func (o *DeleteControlGatewaysGatewayIDNotFound) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *DeleteControlGatewaysGatewayIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteControlGatewaysGatewayIDDefault creates a DeleteControlGatewaysGatewayIDDefault with default headers values
func NewDeleteControlGatewaysGatewayIDDefault(code int) *DeleteControlGatewaysGatewayIDDefault {
	return &DeleteControlGatewaysGatewayIDDefault{
		_statusCode: code,
	}
}

/* DeleteControlGatewaysGatewayIDDefault describes a response with status code -1, with default header values.

unknown error
*/
type DeleteControlGatewaysGatewayIDDefault struct {
	_statusCode int

	Payload *models.APIResponse
}

// Code gets the status code for the delete control gateways gateway ID default response
func (o *DeleteControlGatewaysGatewayIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteControlGatewaysGatewayIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /control/gateways/{gatewayId}][%d] DeleteControlGatewaysGatewayID default  %+v", o._statusCode, o.Payload)
}
func (o *DeleteControlGatewaysGatewayIDDefault) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *DeleteControlGatewaysGatewayIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
