// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIEventsEventIDProvidedSpecDiffParams creates a new GetAPIEventsEventIDProvidedSpecDiffParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIEventsEventIDProvidedSpecDiffParams() *GetAPIEventsEventIDProvidedSpecDiffParams {
	return &GetAPIEventsEventIDProvidedSpecDiffParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIEventsEventIDProvidedSpecDiffParamsWithTimeout creates a new GetAPIEventsEventIDProvidedSpecDiffParams object
// with the ability to set a timeout on a request.
func NewGetAPIEventsEventIDProvidedSpecDiffParamsWithTimeout(timeout time.Duration) *GetAPIEventsEventIDProvidedSpecDiffParams {
	return &GetAPIEventsEventIDProvidedSpecDiffParams{
		timeout: timeout,
	}
}

// NewGetAPIEventsEventIDProvidedSpecDiffParamsWithContext creates a new GetAPIEventsEventIDProvidedSpecDiffParams object
// with the ability to set a context for a request.
func NewGetAPIEventsEventIDProvidedSpecDiffParamsWithContext(ctx context.Context) *GetAPIEventsEventIDProvidedSpecDiffParams {
	return &GetAPIEventsEventIDProvidedSpecDiffParams{
		Context: ctx,
	}
}

// NewGetAPIEventsEventIDProvidedSpecDiffParamsWithHTTPClient creates a new GetAPIEventsEventIDProvidedSpecDiffParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIEventsEventIDProvidedSpecDiffParamsWithHTTPClient(client *http.Client) *GetAPIEventsEventIDProvidedSpecDiffParams {
	return &GetAPIEventsEventIDProvidedSpecDiffParams{
		HTTPClient: client,
	}
}

/* GetAPIEventsEventIDProvidedSpecDiffParams contains all the parameters to send to the API endpoint
   for the get API events event ID provided spec diff operation.

   Typically these are written to a http.Request.
*/
type GetAPIEventsEventIDProvidedSpecDiffParams struct {

	/* EventID.

	   API event ID

	   Format: uint32
	*/
	EventID uint32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API events event ID provided spec diff params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) WithDefaults() *GetAPIEventsEventIDProvidedSpecDiffParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API events event ID provided spec diff params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API events event ID provided spec diff params
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) WithTimeout(timeout time.Duration) *GetAPIEventsEventIDProvidedSpecDiffParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API events event ID provided spec diff params
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API events event ID provided spec diff params
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) WithContext(ctx context.Context) *GetAPIEventsEventIDProvidedSpecDiffParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API events event ID provided spec diff params
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API events event ID provided spec diff params
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) WithHTTPClient(client *http.Client) *GetAPIEventsEventIDProvidedSpecDiffParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API events event ID provided spec diff params
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEventID adds the eventID to the get API events event ID provided spec diff params
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) WithEventID(eventID uint32) *GetAPIEventsEventIDProvidedSpecDiffParams {
	o.SetEventID(eventID)
	return o
}

// SetEventID adds the eventId to the get API events event ID provided spec diff params
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) SetEventID(eventID uint32) {
	o.EventID = eventID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIEventsEventIDProvidedSpecDiffParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param eventId
	if err := r.SetPathParam("eventId", swag.FormatUint32(o.EventID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
