// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDashboardAPIUsageLatestDiffsParams creates a new GetDashboardAPIUsageLatestDiffsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDashboardAPIUsageLatestDiffsParams() *GetDashboardAPIUsageLatestDiffsParams {
	return &GetDashboardAPIUsageLatestDiffsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDashboardAPIUsageLatestDiffsParamsWithTimeout creates a new GetDashboardAPIUsageLatestDiffsParams object
// with the ability to set a timeout on a request.
func NewGetDashboardAPIUsageLatestDiffsParamsWithTimeout(timeout time.Duration) *GetDashboardAPIUsageLatestDiffsParams {
	return &GetDashboardAPIUsageLatestDiffsParams{
		timeout: timeout,
	}
}

// NewGetDashboardAPIUsageLatestDiffsParamsWithContext creates a new GetDashboardAPIUsageLatestDiffsParams object
// with the ability to set a context for a request.
func NewGetDashboardAPIUsageLatestDiffsParamsWithContext(ctx context.Context) *GetDashboardAPIUsageLatestDiffsParams {
	return &GetDashboardAPIUsageLatestDiffsParams{
		Context: ctx,
	}
}

// NewGetDashboardAPIUsageLatestDiffsParamsWithHTTPClient creates a new GetDashboardAPIUsageLatestDiffsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDashboardAPIUsageLatestDiffsParamsWithHTTPClient(client *http.Client) *GetDashboardAPIUsageLatestDiffsParams {
	return &GetDashboardAPIUsageLatestDiffsParams{
		HTTPClient: client,
	}
}

/* GetDashboardAPIUsageLatestDiffsParams contains all the parameters to send to the API endpoint
   for the get dashboard API usage latest diffs operation.

   Typically these are written to a http.Request.
*/
type GetDashboardAPIUsageLatestDiffsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get dashboard API usage latest diffs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDashboardAPIUsageLatestDiffsParams) WithDefaults() *GetDashboardAPIUsageLatestDiffsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get dashboard API usage latest diffs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDashboardAPIUsageLatestDiffsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get dashboard API usage latest diffs params
func (o *GetDashboardAPIUsageLatestDiffsParams) WithTimeout(timeout time.Duration) *GetDashboardAPIUsageLatestDiffsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dashboard API usage latest diffs params
func (o *GetDashboardAPIUsageLatestDiffsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dashboard API usage latest diffs params
func (o *GetDashboardAPIUsageLatestDiffsParams) WithContext(ctx context.Context) *GetDashboardAPIUsageLatestDiffsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dashboard API usage latest diffs params
func (o *GetDashboardAPIUsageLatestDiffsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dashboard API usage latest diffs params
func (o *GetDashboardAPIUsageLatestDiffsParams) WithHTTPClient(client *http.Client) *GetDashboardAPIUsageLatestDiffsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dashboard API usage latest diffs params
func (o *GetDashboardAPIUsageLatestDiffsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDashboardAPIUsageLatestDiffsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
