// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetControlTraceSourcesParams creates a new GetControlTraceSourcesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetControlTraceSourcesParams() *GetControlTraceSourcesParams {
	return &GetControlTraceSourcesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetControlTraceSourcesParamsWithTimeout creates a new GetControlTraceSourcesParams object
// with the ability to set a timeout on a request.
func NewGetControlTraceSourcesParamsWithTimeout(timeout time.Duration) *GetControlTraceSourcesParams {
	return &GetControlTraceSourcesParams{
		timeout: timeout,
	}
}

// NewGetControlTraceSourcesParamsWithContext creates a new GetControlTraceSourcesParams object
// with the ability to set a context for a request.
func NewGetControlTraceSourcesParamsWithContext(ctx context.Context) *GetControlTraceSourcesParams {
	return &GetControlTraceSourcesParams{
		Context: ctx,
	}
}

// NewGetControlTraceSourcesParamsWithHTTPClient creates a new GetControlTraceSourcesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetControlTraceSourcesParamsWithHTTPClient(client *http.Client) *GetControlTraceSourcesParams {
	return &GetControlTraceSourcesParams{
		HTTPClient: client,
	}
}

/* GetControlTraceSourcesParams contains all the parameters to send to the API endpoint
   for the get control trace sources operation.

   Typically these are written to a http.Request.
*/
type GetControlTraceSourcesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get control trace sources params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetControlTraceSourcesParams) WithDefaults() *GetControlTraceSourcesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get control trace sources params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetControlTraceSourcesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get control trace sources params
func (o *GetControlTraceSourcesParams) WithTimeout(timeout time.Duration) *GetControlTraceSourcesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get control trace sources params
func (o *GetControlTraceSourcesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get control trace sources params
func (o *GetControlTraceSourcesParams) WithContext(ctx context.Context) *GetControlTraceSourcesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get control trace sources params
func (o *GetControlTraceSourcesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get control trace sources params
func (o *GetControlTraceSourcesParams) WithHTTPClient(client *http.Client) *GetControlTraceSourcesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get control trace sources params
func (o *GetControlTraceSourcesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetControlTraceSourcesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
