// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openclarity/apiclarity/api/client/models"
)

// PostControlGatewaysReader is a Reader for the PostControlGateways structure.
type PostControlGatewaysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostControlGatewaysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostControlGatewaysCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostControlGatewaysDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostControlGatewaysCreated creates a PostControlGatewaysCreated with default headers values
func NewPostControlGatewaysCreated() *PostControlGatewaysCreated {
	return &PostControlGatewaysCreated{}
}

/* PostControlGatewaysCreated describes a response with status code 201, with default header values.

Success
*/
type PostControlGatewaysCreated struct {
	Payload *models.APIGateway
}

func (o *PostControlGatewaysCreated) Error() string {
	return fmt.Sprintf("[POST /control/gateways][%d] postControlGatewaysCreated  %+v", 201, o.Payload)
}
func (o *PostControlGatewaysCreated) GetPayload() *models.APIGateway {
	return o.Payload
}

func (o *PostControlGatewaysCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIGateway)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostControlGatewaysDefault creates a PostControlGatewaysDefault with default headers values
func NewPostControlGatewaysDefault(code int) *PostControlGatewaysDefault {
	return &PostControlGatewaysDefault{
		_statusCode: code,
	}
}

/* PostControlGatewaysDefault describes a response with status code -1, with default header values.

unknown error
*/
type PostControlGatewaysDefault struct {
	_statusCode int

	Payload *models.APIResponse
}

// Code gets the status code for the post control gateways default response
func (o *PostControlGatewaysDefault) Code() int {
	return o._statusCode
}

func (o *PostControlGatewaysDefault) Error() string {
	return fmt.Sprintf("[POST /control/gateways][%d] PostControlGateways default  %+v", o._statusCode, o.Payload)
}
func (o *PostControlGatewaysDefault) GetPayload() *models.APIResponse {
	return o.Payload
}

func (o *PostControlGatewaysDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
