// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/openclarity/apiclarity/api/client/models"
)

// NewPostAPIInventoryReviewIDApprovedReviewParams creates a new PostAPIInventoryReviewIDApprovedReviewParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIInventoryReviewIDApprovedReviewParams() *PostAPIInventoryReviewIDApprovedReviewParams {
	return &PostAPIInventoryReviewIDApprovedReviewParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIInventoryReviewIDApprovedReviewParamsWithTimeout creates a new PostAPIInventoryReviewIDApprovedReviewParams object
// with the ability to set a timeout on a request.
func NewPostAPIInventoryReviewIDApprovedReviewParamsWithTimeout(timeout time.Duration) *PostAPIInventoryReviewIDApprovedReviewParams {
	return &PostAPIInventoryReviewIDApprovedReviewParams{
		timeout: timeout,
	}
}

// NewPostAPIInventoryReviewIDApprovedReviewParamsWithContext creates a new PostAPIInventoryReviewIDApprovedReviewParams object
// with the ability to set a context for a request.
func NewPostAPIInventoryReviewIDApprovedReviewParamsWithContext(ctx context.Context) *PostAPIInventoryReviewIDApprovedReviewParams {
	return &PostAPIInventoryReviewIDApprovedReviewParams{
		Context: ctx,
	}
}

// NewPostAPIInventoryReviewIDApprovedReviewParamsWithHTTPClient creates a new PostAPIInventoryReviewIDApprovedReviewParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIInventoryReviewIDApprovedReviewParamsWithHTTPClient(client *http.Client) *PostAPIInventoryReviewIDApprovedReviewParams {
	return &PostAPIInventoryReviewIDApprovedReviewParams{
		HTTPClient: client,
	}
}

/* PostAPIInventoryReviewIDApprovedReviewParams contains all the parameters to send to the API endpoint
   for the post API inventory review ID approved review operation.

   Typically these are written to a http.Request.
*/
type PostAPIInventoryReviewIDApprovedReviewParams struct {

	// Body.
	Body *models.ApprovedReview

	// ReviewID.
	//
	// Format: uint32
	ReviewID uint32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API inventory review ID approved review params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIInventoryReviewIDApprovedReviewParams) WithDefaults() *PostAPIInventoryReviewIDApprovedReviewParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API inventory review ID approved review params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIInventoryReviewIDApprovedReviewParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) WithTimeout(timeout time.Duration) *PostAPIInventoryReviewIDApprovedReviewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) WithContext(ctx context.Context) *PostAPIInventoryReviewIDApprovedReviewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) WithHTTPClient(client *http.Client) *PostAPIInventoryReviewIDApprovedReviewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) WithBody(body *models.ApprovedReview) *PostAPIInventoryReviewIDApprovedReviewParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) SetBody(body *models.ApprovedReview) {
	o.Body = body
}

// WithReviewID adds the reviewID to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) WithReviewID(reviewID uint32) *PostAPIInventoryReviewIDApprovedReviewParams {
	o.SetReviewID(reviewID)
	return o
}

// SetReviewID adds the reviewId to the post API inventory review ID approved review params
func (o *PostAPIInventoryReviewIDApprovedReviewParams) SetReviewID(reviewID uint32) {
	o.ReviewID = reviewID
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIInventoryReviewIDApprovedReviewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param reviewId
	if err := r.SetPathParam("reviewId", swag.FormatUint32(o.ReviewID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
