// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteControlTraceSourcesTraceSourceIDHandlerFunc turns a function with the right signature into a delete control trace sources trace source ID handler
type DeleteControlTraceSourcesTraceSourceIDHandlerFunc func(DeleteControlTraceSourcesTraceSourceIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteControlTraceSourcesTraceSourceIDHandlerFunc) Handle(params DeleteControlTraceSourcesTraceSourceIDParams) middleware.Responder {
	return fn(params)
}

// DeleteControlTraceSourcesTraceSourceIDHandler interface for that can handle valid delete control trace sources trace source ID params
type DeleteControlTraceSourcesTraceSourceIDHandler interface {
	Handle(DeleteControlTraceSourcesTraceSourceIDParams) middleware.Responder
}

// NewDeleteControlTraceSourcesTraceSourceID creates a new http.Handler for the delete control trace sources trace source ID operation
func NewDeleteControlTraceSourcesTraceSourceID(ctx *middleware.Context, handler DeleteControlTraceSourcesTraceSourceIDHandler) *DeleteControlTraceSourcesTraceSourceID {
	return &DeleteControlTraceSourcesTraceSourceID{Context: ctx, Handler: handler}
}

/* DeleteControlTraceSourcesTraceSourceID swagger:route DELETE /control/traceSources/{traceSourceId} deleteControlTraceSourcesTraceSourceId

Delete a Trace Source

*/
type DeleteControlTraceSourcesTraceSourceID struct {
	Context *middleware.Context
	Handler DeleteControlTraceSourcesTraceSourceIDHandler
}

func (o *DeleteControlTraceSourcesTraceSourceID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteControlTraceSourcesTraceSourceIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
