// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openclarity/apiclarity/api/server/models"
)

// GetAPIInventoryAPIIDHostPortOKCode is the HTTP code returned for type GetAPIInventoryAPIIDHostPortOK
const GetAPIInventoryAPIIDHostPortOKCode int = 200

/*GetAPIInventoryAPIIDHostPortOK Success

swagger:response getApiInventoryApiIdHostPortOK
*/
type GetAPIInventoryAPIIDHostPortOK struct {

	/*api id
	  In: Body
	*/
	Payload uint32 `json:"body,omitempty"`
}

// NewGetAPIInventoryAPIIDHostPortOK creates GetAPIInventoryAPIIDHostPortOK with default headers values
func NewGetAPIInventoryAPIIDHostPortOK() *GetAPIInventoryAPIIDHostPortOK {

	return &GetAPIInventoryAPIIDHostPortOK{}
}

// WithPayload adds the payload to the get Api inventory Api Id host port o k response
func (o *GetAPIInventoryAPIIDHostPortOK) WithPayload(payload uint32) *GetAPIInventoryAPIIDHostPortOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api inventory Api Id host port o k response
func (o *GetAPIInventoryAPIIDHostPortOK) SetPayload(payload uint32) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIInventoryAPIIDHostPortOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetAPIInventoryAPIIDHostPortDefault unknown error

swagger:response getApiInventoryApiIdHostPortDefault
*/
type GetAPIInventoryAPIIDHostPortDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetAPIInventoryAPIIDHostPortDefault creates GetAPIInventoryAPIIDHostPortDefault with default headers values
func NewGetAPIInventoryAPIIDHostPortDefault(code int) *GetAPIInventoryAPIIDHostPortDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAPIInventoryAPIIDHostPortDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get API inventory API ID host port default response
func (o *GetAPIInventoryAPIIDHostPortDefault) WithStatusCode(code int) *GetAPIInventoryAPIIDHostPortDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get API inventory API ID host port default response
func (o *GetAPIInventoryAPIIDHostPortDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get API inventory API ID host port default response
func (o *GetAPIInventoryAPIIDHostPortDefault) WithPayload(payload *models.APIResponse) *GetAPIInventoryAPIIDHostPortDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get API inventory API ID host port default response
func (o *GetAPIInventoryAPIIDHostPortDefault) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIInventoryAPIIDHostPortDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
