// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openclarity/apiclarity/api/server/models"
)

// GetAPIInventoryAPIIDSuggestedReviewOKCode is the HTTP code returned for type GetAPIInventoryAPIIDSuggestedReviewOK
const GetAPIInventoryAPIIDSuggestedReviewOKCode int = 200

/*GetAPIInventoryAPIIDSuggestedReviewOK Success

swagger:response getApiInventoryApiIdSuggestedReviewOK
*/
type GetAPIInventoryAPIIDSuggestedReviewOK struct {

	/*
	  In: Body
	*/
	Payload *models.SuggestedReview `json:"body,omitempty"`
}

// NewGetAPIInventoryAPIIDSuggestedReviewOK creates GetAPIInventoryAPIIDSuggestedReviewOK with default headers values
func NewGetAPIInventoryAPIIDSuggestedReviewOK() *GetAPIInventoryAPIIDSuggestedReviewOK {

	return &GetAPIInventoryAPIIDSuggestedReviewOK{}
}

// WithPayload adds the payload to the get Api inventory Api Id suggested review o k response
func (o *GetAPIInventoryAPIIDSuggestedReviewOK) WithPayload(payload *models.SuggestedReview) *GetAPIInventoryAPIIDSuggestedReviewOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Api inventory Api Id suggested review o k response
func (o *GetAPIInventoryAPIIDSuggestedReviewOK) SetPayload(payload *models.SuggestedReview) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIInventoryAPIIDSuggestedReviewOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetAPIInventoryAPIIDSuggestedReviewDefault unknown error

swagger:response getApiInventoryApiIdSuggestedReviewDefault
*/
type GetAPIInventoryAPIIDSuggestedReviewDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetAPIInventoryAPIIDSuggestedReviewDefault creates GetAPIInventoryAPIIDSuggestedReviewDefault with default headers values
func NewGetAPIInventoryAPIIDSuggestedReviewDefault(code int) *GetAPIInventoryAPIIDSuggestedReviewDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAPIInventoryAPIIDSuggestedReviewDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get API inventory API ID suggested review default response
func (o *GetAPIInventoryAPIIDSuggestedReviewDefault) WithStatusCode(code int) *GetAPIInventoryAPIIDSuggestedReviewDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get API inventory API ID suggested review default response
func (o *GetAPIInventoryAPIIDSuggestedReviewDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get API inventory API ID suggested review default response
func (o *GetAPIInventoryAPIIDSuggestedReviewDefault) WithPayload(payload *models.APIResponse) *GetAPIInventoryAPIIDSuggestedReviewDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get API inventory API ID suggested review default response
func (o *GetAPIInventoryAPIIDSuggestedReviewDefault) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAPIInventoryAPIIDSuggestedReviewDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
