// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIInventoryAPIIDHostPortParams creates a new GetAPIInventoryAPIIDHostPortParams object
//
// There are no default values defined in the spec.
func NewGetAPIInventoryAPIIDHostPortParams() GetAPIInventoryAPIIDHostPortParams {

	return GetAPIInventoryAPIIDHostPortParams{}
}

// GetAPIInventoryAPIIDHostPortParams contains all the bound params for the get API inventory API ID host port operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetAPIInventoryAPIIDHostPort
type GetAPIInventoryAPIIDHostPortParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*api host name
	  Required: true
	  In: path
	*/
	Host string
	/*api port
	  Required: true
	  In: path
	*/
	Port string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAPIInventoryAPIIDHostPortParams() beforehand.
func (o *GetAPIInventoryAPIIDHostPortParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rHost, rhkHost, _ := route.Params.GetOK("host")
	if err := o.bindHost(rHost, rhkHost, route.Formats); err != nil {
		res = append(res, err)
	}

	rPort, rhkPort, _ := route.Params.GetOK("port")
	if err := o.bindPort(rPort, rhkPort, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindHost binds and validates parameter Host from path.
func (o *GetAPIInventoryAPIIDHostPortParams) bindHost(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Host = raw

	return nil
}

// bindPort binds and validates parameter Port from path.
func (o *GetAPIInventoryAPIIDHostPortParams) bindPort(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Port = raw

	return nil
}
