// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openclarity/apiclarity/api/server/models"
)

// GetDashboardAPIUsageMostUsedOKCode is the HTTP code returned for type GetDashboardAPIUsageMostUsedOK
const GetDashboardAPIUsageMostUsedOKCode int = 200

/*GetDashboardAPIUsageMostUsedOK Success

swagger:response getDashboardApiUsageMostUsedOK
*/
type GetDashboardAPIUsageMostUsedOK struct {

	/*
	  In: Body
	*/
	Payload []*models.APICount `json:"body,omitempty"`
}

// NewGetDashboardAPIUsageMostUsedOK creates GetDashboardAPIUsageMostUsedOK with default headers values
func NewGetDashboardAPIUsageMostUsedOK() *GetDashboardAPIUsageMostUsedOK {

	return &GetDashboardAPIUsageMostUsedOK{}
}

// WithPayload adds the payload to the get dashboard Api usage most used o k response
func (o *GetDashboardAPIUsageMostUsedOK) WithPayload(payload []*models.APICount) *GetDashboardAPIUsageMostUsedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dashboard Api usage most used o k response
func (o *GetDashboardAPIUsageMostUsedOK) SetPayload(payload []*models.APICount) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDashboardAPIUsageMostUsedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.APICount, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetDashboardAPIUsageMostUsedDefault unknown error

swagger:response getDashboardApiUsageMostUsedDefault
*/
type GetDashboardAPIUsageMostUsedDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetDashboardAPIUsageMostUsedDefault creates GetDashboardAPIUsageMostUsedDefault with default headers values
func NewGetDashboardAPIUsageMostUsedDefault(code int) *GetDashboardAPIUsageMostUsedDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDashboardAPIUsageMostUsedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get dashboard API usage most used default response
func (o *GetDashboardAPIUsageMostUsedDefault) WithStatusCode(code int) *GetDashboardAPIUsageMostUsedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get dashboard API usage most used default response
func (o *GetDashboardAPIUsageMostUsedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get dashboard API usage most used default response
func (o *GetDashboardAPIUsageMostUsedDefault) WithPayload(payload *models.APIResponse) *GetDashboardAPIUsageMostUsedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get dashboard API usage most used default response
func (o *GetDashboardAPIUsageMostUsedDefault) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDashboardAPIUsageMostUsedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
