// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAPIEventsEventIDProvidedSpecDiffHandlerFunc turns a function with the right signature into a get API events event ID provided spec diff handler
type GetAPIEventsEventIDProvidedSpecDiffHandlerFunc func(GetAPIEventsEventIDProvidedSpecDiffParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIEventsEventIDProvidedSpecDiffHandlerFunc) Handle(params GetAPIEventsEventIDProvidedSpecDiffParams) middleware.Responder {
	return fn(params)
}

// GetAPIEventsEventIDProvidedSpecDiffHandler interface for that can handle valid get API events event ID provided spec diff params
type GetAPIEventsEventIDProvidedSpecDiffHandler interface {
	Handle(GetAPIEventsEventIDProvidedSpecDiffParams) middleware.Responder
}

// NewGetAPIEventsEventIDProvidedSpecDiff creates a new http.Handler for the get API events event ID provided spec diff operation
func NewGetAPIEventsEventIDProvidedSpecDiff(ctx *middleware.Context, handler GetAPIEventsEventIDProvidedSpecDiffHandler) *GetAPIEventsEventIDProvidedSpecDiff {
	return &GetAPIEventsEventIDProvidedSpecDiff{Context: ctx, Handler: handler}
}

/* GetAPIEventsEventIDProvidedSpecDiff swagger:route GET /apiEvents/{eventId}/providedSpecDiff getApiEventsEventIdProvidedSpecDiff

Get API event provided spec diff

*/
type GetAPIEventsEventIDProvidedSpecDiff struct {
	Context *middleware.Context
	Handler GetAPIEventsEventIDProvidedSpecDiffHandler
}

func (o *GetAPIEventsEventIDProvidedSpecDiff) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPIEventsEventIDProvidedSpecDiffParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
