// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetDashboardAPIUsageHandlerFunc turns a function with the right signature into a get dashboard API usage handler
type GetDashboardAPIUsageHandlerFunc func(GetDashboardAPIUsageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDashboardAPIUsageHandlerFunc) Handle(params GetDashboardAPIUsageParams) middleware.Responder {
	return fn(params)
}

// GetDashboardAPIUsageHandler interface for that can handle valid get dashboard API usage params
type GetDashboardAPIUsageHandler interface {
	Handle(GetDashboardAPIUsageParams) middleware.Responder
}

// NewGetDashboardAPIUsage creates a new http.Handler for the get dashboard API usage operation
func NewGetDashboardAPIUsage(ctx *middleware.Context, handler GetDashboardAPIUsageHandler) *GetDashboardAPIUsage {
	return &GetDashboardAPIUsage{Context: ctx, Handler: handler}
}

/* GetDashboardAPIUsage swagger:route GET /dashboard/apiUsage getDashboardApiUsage

Get API usage

*/
type GetDashboardAPIUsage struct {
	Context *middleware.Context
	Handler GetDashboardAPIUsageHandler
}

func (o *GetDashboardAPIUsage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetDashboardAPIUsageParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
