// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/openclarity/apiclarity/api/server/models"
)

// GetAPIEventsHandlerFunc turns a function with the right signature into a get API events handler
type GetAPIEventsHandlerFunc func(GetAPIEventsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAPIEventsHandlerFunc) Handle(params GetAPIEventsParams) middleware.Responder {
	return fn(params)
}

// GetAPIEventsHandler interface for that can handle valid get API events params
type GetAPIEventsHandler interface {
	Handle(GetAPIEventsParams) middleware.Responder
}

// NewGetAPIEvents creates a new http.Handler for the get API events operation
func NewGetAPIEvents(ctx *middleware.Context, handler GetAPIEventsHandler) *GetAPIEvents {
	return &GetAPIEvents{Context: ctx, Handler: handler}
}

/* GetAPIEvents swagger:route GET /apiEvents getApiEvents

Get API events

*/
type GetAPIEvents struct {
	Context *middleware.Context
	Handler GetAPIEventsHandler
}

func (o *GetAPIEvents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAPIEventsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAPIEventsOKBody get API events o k body
//
// swagger:model GetAPIEventsOKBody
type GetAPIEventsOKBody struct {

	// List of API events in the given time range, filters and page. List length must be lower or equal to pageSize
	Items []*models.APIEvent `json:"items"`

	// Total events count in the given time range and filters
	// Required: true
	Total *int64 `json:"total"`
}

// Validate validates this get API events o k body
func (o *GetAPIEventsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTotal(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAPIEventsOKBody) validateItems(formats strfmt.Registry) error {
	if swag.IsZero(o.Items) { // not required
		return nil
	}

	for i := 0; i < len(o.Items); i++ {
		if swag.IsZero(o.Items[i]) { // not required
			continue
		}

		if o.Items[i] != nil {
			if err := o.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getApiEventsOK" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *GetAPIEventsOKBody) validateTotal(formats strfmt.Registry) error {

	if err := validate.Required("getApiEventsOK"+"."+"total", "body", o.Total); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get API events o k body based on the context it is used
func (o *GetAPIEventsOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateItems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAPIEventsOKBody) contextValidateItems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Items); i++ {

		if o.Items[i] != nil {
			if err := o.Items[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getApiEventsOK" + "." + "items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetAPIEventsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAPIEventsOKBody) UnmarshalBinary(b []byte) error {
	var res GetAPIEventsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
